### ISSUE TITLE
Can you publish this to pip?

### ISSUE THREAD

**Issue by niftylettuce** [danielsen/arf#1]
Thanks for your work @danielsen

**Comment by danielsen** [comment]
Sure. I can get it out sometime in the next day or so.

**Comment by niftylettuce** [comment]
is it still `import arf`?

**Comment by danielsen** [comment]
@niftylettuce This is out on PyPi now. The package name `arf` was already taken so it's published as `arf-mime`. Nothing about the module itself changed though so if you install via `pip` there shouldn't be a need change any of your existing code.

 https://pypi.org/project/arf-mime/1.1.0/

**Comment by danielsen** [comment]
Correct, `import arf` is still the way to go.
